title: Jinn # your name (or website title) here
logo: "/images/ProfilePic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Gameplay Programmer learning in University of Wollongong (KDU University College).
  Currently in Y3S2 learning Data Communication and Networking.
  Y3S3 will be my Intership semester.
  <br><br>
  Knowledge
- Logic, Math and Physics for Games,
- Data Structures and Algorithms,
- 2D Game Programming,
- Object Oriented Systems Analysis & Design,
- Object Oriented Programming,
- Mobile Game Development,
- Graphics Programming,
- 3D Game Programming,
- Artificial Intelligence(AI) for Games,
- Game Engine Architecture and Design
- Game Narrative,
- Game World Creation 
  
  <br><br>
  <a href="https://www.linkedin.com/in/fjinnphang/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
