title: Jinn # your name (or website title) here
logo: "/images/ProfilePic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A BSc Psychology Graduate and Gameplay Programmer studying in University of Wollongong Malaysia KDU.
  <br><br>
  Currently looking for Internship/Full-time Gameplay Programmer.
  
  <br><br>
  <a href="https://www.linkedin.com/in/fjinnphang/">More About ME</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
