title: <href= "https://fjinn.github.io/"> Jinn # your name (or website title) here
logo: "/images/ProfilePic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A BSc Psychology Graduate and Bachelor of Game Development Fresh Graduate.
  <br><br>
  A quick learner and gamer full with passions.
  <br><br>
  Do visit my LinkedIn for more about me. 
  <br><br>

github:
  linkedIn: https://www.linkedin.com/in/fjinnphang/
theme: jekyll-theme-dinky
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
