title: Jinn # your name (or website title) here
logo: "/images/ProfilePic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Gameplay Programmer 
  <br><br>
  Has experience on Unity, Unreal, OpenGL 
  <br><br>
  <a href="https://www.linkedin.com/in/fjinnphang/">View My LinkedIn Profile</a> 
   <section class="colorlib-skills" data-section="skills">
        <div class="colorlib-narrow-content">
            <div class="row">
				<div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
						<!--	<span class="heading-meta">My Specialty</span> -->
				    <h2>Skills</h2>
                    <hr>
				</div>
            </div>
            <p>Some of the significant aptitudes which will assist me with achieving your objectives.</p>
            <div class="row">
				<div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
				    <div class="progress-wrap">
				        <h3 style="font-weight: 500;">C/C++(STL)</h3>
				        <div class="progress">
				            <div class="progress-bar color-1" role="progressbar" aria-valuenow="80"
								  	aria-valuemin="0" aria-valuemax="100" style="width:80%">
								<span>80%</span>
				            </div>
                        </div>
				    </div>
				</div>
				<div class="col-md-6 animate-box" data-animate-effect="fadeInRight">
				    <div class="progress-wrap">
				        <h3 style="font-weight: 500;">Python/Django</h3>
				        <div class="progress">
				            <div class="progress-bar color-2" role="progressbar" aria-valuenow="40"
                                 aria-valuemin="0" aria-valuemax="100" style="width:40%">
				                <span>40%</span>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
				    <div class="progress-wrap">
				        <h3 style="font-weight: 500;">Angular 6,7</h3>
				        <div class="progress">
				            <div class="progress-bar color-3" role="progressbar" aria-valuenow="30"
								  	aria-valuemin="0" aria-valuemax="100" style="width:30%">
				                <span>30%</span>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="col-md-6 animate-box" data-animate-effect="fadeInRight">
				    <div class="progress-wrap">
				        <h3 style="font-weight: 500;">Spring-boot</h3>
				        <div class="progress">
				            <div class="progress-bar color-4" role="progressbar" aria-valuenow="20"
								  	aria-valuemin="0" aria-valuemax="100" style="width:20%">
								<span>20%</span>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
				    <div class="progress-wrap">
				        <h3 style="font-weight: 500;">Java/Android</h3>
				            <div class="progress">
								<div class="progress-bar color-5" role="progressbar" aria-valuenow="50"
								  	aria-valuemin="0" aria-valuemax="100" style="width:50%">
								    <span>50%</span>
								</div>
				            </div>
				    </div>
				</div>
				<div class="col-md-6 animate-box" data-animate-effect="fadeInRight">
				    <div class="progress-wrap">
				        <h3 style="font-weight: 500;">MySQL/MongoDB</h3>
				        <div class="progress">
				            <div class="progress-bar color-6" role="progressbar" aria-valuenow="50"
								  	aria-valuemin="0" aria-valuemax="100" style="width:50%">
								<span>50%</span>
				            </div>
				        </div>
				    </div>
				</div>
                <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
				    <div class="progress-wrap">
				        <h3 style="font-weight: 500;">GitHub</h3>
				            <div class="progress">
								<div class="progress-bar color-7" role="progressbar" aria-valuenow="70"
								  	aria-valuemin="0" aria-valuemax="100" style="width:70%">
								    <span>70%</span>
								</div>
				            </div>
				    </div>
				</div>
                <div class="col-md-6 animate-box" data-animate-effect="fadeInRight">
				    <div class="progress-wrap">
				        <h3 style="font-weight: 500;">Nodejs</h3>
				        <div class="progress">
				            <div class="progress-bar color-3" role="progressbar" aria-valuenow="20"
								  	aria-valuemin="0" aria-valuemax="100" style="width:20%">
				                <span>20%</span>
				            </div>
				        </div>
				    </div>
				</div>
            </div>
        </div>
    </section>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
