title: Jinn # your name (or website title) here
logo: "/images/ProfilePic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Gameplay Programmer learning in University of Wollongong (KDU University College).
  <br><br>
  Currently in Y3S2 learning Data Communication and Networking.
  <br><br>
  Y3S3 will be my Intership semester.
  <br><br>
  Has experience of Unity, Unreal Engine, OpenGL
  
  <br><br>
  <a href="https://www.linkedin.com/in/fjinnphang/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
